var missouri_cities = {
  "Affton": "Allowed, no limits. As an unincorporated census-designated place in St. Louis County, Affton follows the county ordinances regarding chickens.",
  "Arnold": "Allowed on 1+ acre, with permit if within 150 feet of a building not on your property.",
  "Ballwin": "Allowed on 2+ acres.",
  "Bayless": "Allowed. No limits. St. Louis County ordinance applies.",
  "Bella Villa": "Allowed. No limits.",
  "Bellefontaine Neighbors": "Allowed. No limit.",
  "Bellerive": "Not allowed.",
  "Bel-Nor": "Up to 7 allowed with annual permit ($25). ",
  "Berkeley": "Not allowed.",
  "Black Jack": "Up to six hens allowed with permit ($50).",
  "Bonne Terre": "Not allowed",
  "Breckenridge Hills": "Not allowed.",
  "Brentwood": "Up to six allowed with permit.",
  "Bridgeton": "Up to six hens with permit. More allowed on larger lots.",
  "Calverton Park": "Up to 6 hens allowed (depending on backyard size) with permit ($10).",
  "Castle Point": "Allowed, no limits. As an unincorporated census-designated place in St. Louis County, Castle Point follows the county ordinances regarding chickens.",
  "Cedar Hill": "Allowed, no limits. As an unincorporated census-designated place in Jefferson County, Cedar Hill follows the county ordinances regarding chickens.",
  "Charlack": "Allowed only if zoned agricultural.",
  "Chesterfield": "Allowed on 2+ acres.",
  "Clarkson Valley": "Allowed on 3+ acres.",
  "Clayton": 'Up to 10 hens allowed with permit ($50, good for 3 years). Additional regulations addressing coop location, craftsmanship, and visibility, as well as maintenance can be found <a href="https://ecode360.com/27564464">here</a>.',
  "Concord": "Allowed, no limits. As an unincorporated census-designated place in St. Louis County, Concord follows the county ordinances regarding chickens.",
  "Cool Valley": "Not allowed.",
  "Cottleville": "Up to four hens allowed.",
  "Crestwood": "Up to five hens allowed with permit. $10 fee",
  "Creve Coeur": "Up to 8 hens allowed on lots 17+ acres. One additional hen allowed for each 2500 additional square feet, up to 12 hens.",
  "Crystal City": "Up to three chickens allowed (as part of the 3 pet limit).",
  "Crystal Lake Park": "Allowed",
  "Dardenne Prarie": "Allowed on lots of 3+ acres zoned R1-A.",
  "Defiance": "Up to four hens allowed. St. Charles County ordinances apply.",
  "De Soto": "Up to six hens allowed with permit.",
  "Des Peres": "Allowed on 4+ acres. Limit of one per 1/5 acre.",
  "Ellisville": "Up to four hens allowed with permit ($10).",
  "Elsberry": "Not allowed in city limits, but people have approached the board to change the ordinance.",
  "Eureka": "Six hens allowed on .23 or more acres.",
  "Fenton": "Allowed. No limit.",
  "Ferguson": "Up to six hens allowed on lots less than 10,000 square feet, with permit ($3/hen). One additional hen allowed per additional 10,000 square feet.",
  "Festus": "Up to four hens allowed with permit on lots a half acre or larger.",
  "Flint Hill": "Not allowed.",
  "Florissant": "Up to four hens allowed with permit.",
  "Foristell": "Allowed.",
  "Frontenac": "Up to five hens allowed with permit.",
  "Glasgow Village": "Allowed, no limits. As an unincorporated census-designated place in St. Louis County, Glasgow Village follows the county ordinances regarding chickens.",
  "Glendale": "Allowed with permit.",
  "Grantwood Village": "Up to four hens allowed with permit.",
  "Green Park": "Not allowed.",
  "Greendale": "Not allowed.",
  "Harvester": "Up to four hens allowed. St. Charles County ordinances apply.",
  "Hawk Point": "Not allowed in city limits.",
  "Hazelwood": 'Allowed with permit. Some restrictions apply; see <a href="https://ecode360.com/31294424">here</a> for more information.',
  "Hillsboro": "Allowed with permit on 1+ acre lots, must be 200 ft from adjacent dwellings.",
  "House Springs": "Allowed, no limits. As an unincorporated census-designated place in Jefferson County, House Springs follows the county ordinances regarding chickens.",
  "Huntleigh": "Not allowed",
  "Imperial": "Allowed, no limits. As an unincorporated census-designated place in Jefferson County, Imperial follows the Jefferson County ordinances regarding chickens.",
  "Jefferson County (Unincorporated)": "Allowed, no limits.",
  "Jennings": "Not allowed.",
  "Kennett": "Allowed, no limits.",
  "Kirkwood": "Allowed, no limits.",
  "Ladue": "Allowed. No limits.",
  "Lake St. Louis": "Up to four allowed.<br />Not allowed in Lake St. Louis Community Association.",
  "Lemay": "Allowed, no limits. As an unincorporated census-designated place in St. Louis County, Lemay follows the county ordinances regarding chickens.",
  "Manchester": "Allowed on 2+ acres.",
  "Maplewood": "Up to six hens allowed with permit.",
  "Marthasville": "Allowed only if zoned Agricultural.",
  "Maryland Heights": "Up to 4 hens allowed on residential properties.",
  "Matson": "Up to four hens allowed. St. Charles County ordinances apply.",
  "Mehlville": "Allowed, no limits. As an unincorporated census-designated place in St. Louis County, Mehlville follows the county ordinances regarding chickens.",
  "Moline Acres": "Not allowed.",
  "Normandy": "Not allowed.",
  "Northwoods": "Allowed.",
  "O'Fallon": "Not allowed.",
  "Oakville": "Allowed, no limits. As an unincorporated census-designated place in St. Louis County, Oakville follows the county ordinances regarding chickens.",
  "Old Jamestown": "Allowed, no limits. As an unincorporated census-designated place in St. Louis County, Old Jamestown follows the county ordinances regarding chickens.",
  "Olivette": "Allowed.",
  "Orchard Farm": "Up to four hens allowed. St. Charles County ordinances apply.",
  "Overland": "8 hens allowed on 5500+ sq. ft. of unimproved land.",
  "Pacific": "Allowed only in areas zoned non-urban (NU).",
  "Pagedale": "Not allowed.",
  "Pasadena Hills": "Allowed.",
  "Richmond Heights": "Up to five hens allowed with permit ($25).",
  "Riverview": "Up to eight hens allowed with permit ($15).",
  "Rock Hill": 'Up to 6 hens allowed with permit (3 years, $30 inspection). Coop regulations apply. See ordinance <a href="https://ecode360.com/27955532">here</a>.',
  "Sappington": "Allowed, no limits. As an unincorporated census-designated place in St. Louis County, Sappington follows the county ordinances regarding chickens.",
  "Shrewsbury": "Up to five hens allowed with permit ($30).",
  "Spanish Lake": "Allowed, no limits. As an unincorporated census-designated place in St. Louis County, Spanish Lake follows the county ordinances regarding chickens.",
  "St Ann": "Not currently allowed, but a legal challenge to the ordinance is in process.",
  "St Charles": "Allowed. 8-12 hens, depending on lot size.",
  "St Clair": "Not allowed in city limits.",
  "St George": "Allowed, no limits. As an unincorporated census-designated place in St. Louis County, St. George follows the county ordinances regarding chickens.",
  "St Louis": 'Up to eight hens allowed under <a href="https://theeasychicken.com/sites/chicken/files/st._louis_city_chicken_ordinance_2017.pdf">2017 Chicken Ordinance</a>.',
  "St John": '<a href="https://www.ecode360.com/29083691">Not allowed.</a>',
  "St Paul": "Allowed, no limits.",
  "St Peters": "Not allowed.",
  "Sunset Hills": "Allowed. No limits.",
  "Town and Country": "Not allowed.",
  "Troy": "Not allowed.",
  "Twin Oaks": "Not allowed.",
  "University City": "Up to seven hens allowed with permit ($50) and quarterly inspections ($25/ea.) ",
  "Valley Park": "Allowed with permit ($10).",
  "Velda City": "Not allowed.",
  "Village of Sycamore Hills": "Not currently allowed, but they are revisiting the ordinance due to the volume of requests for backyard chickens.",
  "Vinita Park": "Up to 15 allowed with permit.",
  "Warren County (Unincorporated)": "Allowed, no limits.",
  "Warrensburg": "Allowed",
  "Warrenton": "Not allowed.",
  "Warson Woods": "Not allowed.",
  "Webster Groves": "Up to eight hens allowed on 5,500 square feet unimproved land with permit ($30).",
  "Weldon Springs": "Allowed in AG district only.",
  "Wentzville": "Not allowed.",
  "Westwood": "Allowed",
  "Wilbur Park": "Not allowed.",
  "Wildwood": "Allowed on non-urban (NU) and R-1 zoned lots that are 5+ acres. Accommodations possible for smaller lots.",
  "Winchester": "Not allowed.",
  "Wright City": "Allowed",
  "Union": 'Allowed as a farm operation only, with proper zoning. See regulations <a href="https://ecode360.com/27862390">here</a>&nbsp;and <a href="https://ecode360.com/27862969">here</a>.'
};


var illinois_cities = {
  "Alton": "Up to 5 hens allowed with permit ($25).",
  "Belleville": "Not allowed",
  "Collinsville": "Allowed with permit ($50,&nbsp;limited to 75 permits total). Limit of 6 hens.",
  "Edwardsville": "Allowed on limited basis during a 2 year trial period starting in 2018. Permits are $50 the first year and $25/year after.",
  "Fairview Heights": "Allowed",
  "Freeburg": "Not allowed",
  "Girard": "Not allowed in city limits",
  "Marissa": "Up to six with permit ($25)",
  "Mascoutah": "Not allowed",
  "O'Fallon": "Allowed if zoned Agricultural (unlimited) or Rural Residential (6 hens per acre, limit of 12)",
  "Swansea": "Four hens allowed with annual permit ($10)",
  "Troy": "Allowed only in agricultural zone",
  "Waterloo": "Not allowed",
  "Worden": "Not allowed."
};

var missouri_counties = {
  "Jefferson County": "Allowed, no limits.",
  "St. Charles County": 'Up to four hens allowed as part of a four pet total. See ordinance <a href="https://ecode360.com/30840429" target="_blank">here</a>',
  "St. Louis County": "Allowed, no limits.",
  "Warren County": "Allowed, no limits."
}

var illinois_counties = {
  "Franklin County": "Allowed, no limits.",
  "Madison County": "Up to 5 allowed with permit ($300).",
  "St. Clair County": "Not allowed."
}

var source_url = "https://theeasychicken.com/regulations";